# pyuvm test for the counter (see the build appendix). Same recipe as cocotb.
EXAMPLE_LANG := cocotb
TOP          := counter
SOURCES      := ../rtl/counter.sv
TEST_MODULE  := test_counter_pyuvm
include ../../common.mk
