# UVM-SystemC smoke test for the counter (see the build appendix).
# Needs UVM_SYSTEMC_HOME pointing at an installed Accellera UVM-SystemC.
EXAMPLE_LANG := systemc
TOP          := counter_uvmsc_tb
SOURCES      := sc_main.cpp
REQUIRES     := uvm-systemc
include ../../common.mk
